# Generated by Django 6.0.2 on 2026-02-18 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_payment_payment_method_alter_payment_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
